[facemask]
    facemask_points = [151, 299, 298, 411, 410, 11, 186, 187, 68, 69]
    left_eye_points = [226,113,225,224,223,222,221,189,245,233,232,231,230,229,228,31]
    right_eye_points = [446,342,445,444,443,442,441,413,465,453,452,451,450,449,448,446]

    head_pose_points = [1,  #Nose 
                        199,# Chin
                        33, # Left Eye
                        263,# Right Eye
                        61, # Left Mouth
                        291 # Right Mouth
                        ]
    map_face_base = [[0, 0, 0],             # Nose tip
                     [0.0, -330.0, -65.0],        # Chin
                     [-225.0, 170.0, -135.0],     # Left eye left corner
                     [225.0, 170.0, -135.0],      # Right eye right corner
                     [-150.0, -150.0, -125.0],    # Left Mouth corner
                     [150.0, -150.0, -125.0]      # Right mouth corner
                  ]

[signal]
    length_samples = 256
    fps = 30 
